apiVersion: v2
name: jetscale-stack
description: The JetScale Platform Umbrella Chart
type: application
version: 0.1.5
appVersion: "1.0.0"

dependencies:
  # Backend Service (Proprietary OCI)
  - name: backend-api
    version: "1.1.7"
    # Point to the parent namespace, Helm appends the name
    repository: "oci://ghcr.io/jetscale-ai/charts"
    condition: backend-api.enabled

  # Frontend Service (Proprietary OCI)
  - name: frontend-web
    version: "1.0.7"
    # Point to the parent namespace, Helm appends the name
    repository: "oci://ghcr.io/jetscale-ai/charts"
    condition: frontend-web.enabled
