apiVersion: v2
name: jetscale-stack
description: The JetScale Platform Umbrella Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Backend Service
  - name: backend-api
    version: 0.1.0
    repository: "file://../../../backend/charts/backend-api"
    condition: backend-api.enabled

  # Frontend Service
  - name: frontend-web
    version: 0.1.0
    repository: "file://../../../frontend/charts/frontend-web"
    condition: frontend-web.enabled
