apiVersion: v2
name: jetscale
description: The JetScale Platform Umbrella Chart
type: application
version: 0.15.2
appVersion: "0.15.2"
dependencies:
  # Backend Service (Proprietary OCI)
  - name: backend
    alias: backend-api
    repository: "oci://ghcr.io/jetscale-ai/charts"
    version: "3.1.4"
    condition: backend-api.enabled
  - name: backend
    alias: backend-ws
    repository: "oci://ghcr.io/jetscale-ai/charts"
    version: "3.1.4"
    condition: backend-ws.enabled
  # Frontend Service (Proprietary OCI)
  - name: frontend
    repository: "oci://ghcr.io/jetscale-ai/charts"
    version: "2.1.2"
    condition: frontend.enabled
