apiVersion: v2
name: jetscale
description: The JetScale Platform Umbrella Chart
type: application
version: 0.2.1
appVersion: "1.0.0"

dependencies:
  # Backend Service (Proprietary OCI)
  - name: backend
    alias: backend-api
    # Point to the parent namespace, Helm appends the name
    repository: "oci://ghcr.io/jetscale-ai/charts"
    # repository: "file://../../../Backend/chart"
    version: "3.0.1"
    condition: backend-api.enabled
  - name: backend
    alias: backend-ws
    # Point to the parent namespace, Helm appends the name
    repository: "oci://ghcr.io/jetscale-ai/charts"
    # repository: "file://../../../Backend/chart"
    version: "3.0.1"
    condition: backend-ws.enabled

  # Frontend Service (Proprietary OCI)
  - name: frontend
    # Point to the parent namespace, Helm appends the name
    repository: "oci://ghcr.io/jetscale-ai/charts"
    # repository: "file://../../../Frontend/chart"
    version: "2.0.7"
    condition: frontend.enabled
