# ==========================================================
# TEST: CI REMOTE (GitHub Actions)
# Base: values.test.yaml
# ==========================================================
global:
  env: "ci-kind"

backend-api:
  imagePullSecrets:
    - name: ghcr-registry-secret
  image:
    repository: ghcr.io/jetscale-ai/backend
    tag: "4.6.12"
    pullPolicy: Always
  env:
    JETSCALE_APP_NAME: "JetScale Backend (CI)"
    JETSCALE_JWT_SECRET_KEY: "ci-kind-jwt-secret"

backend-ws:
  imagePullSecrets:
    - name: ghcr-registry-secret
  image:
    repository: ghcr.io/jetscale-ai/backend
    tag: "4.6.12"
    pullPolicy: Always
  env:
    JETSCALE_APP_NAME: "JetScale Backend (CI)"
    JETSCALE_JWT_SECRET_KEY: "ci-kind-jwt-secret"

frontend:
  imagePullSecrets:
    - name: ghcr-registry-secret
  image:
    repository: ghcr.io/jetscale-ai/frontend
    tag: "2.7.1"
    pullPolicy: Always
