{{- $testSecrets := .Values.testSecrets | default dict -}}
{{- if $testSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  labels:
    {{- include "jetscale.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "jetscale.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    {{- include "jetscale.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-client-secret
  labels:
    {{- include "jetscale.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-common-secrets
  labels:
    {{- include "jetscale.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PLACEHOLDER: "true"
{{- end }}
