---
# Source: jetscale/templates/ext-secret-app.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "jetscale-app-secrets"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "jetscale-secrets-store-staging"
    kind: SecretStore
  target:
    name: jetscale-app-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "jetscale-staging/application/config"
