---
# Source: jetscale/templates/httproute.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-jetscale
  labels:
    helm.sh/chart: jetscale-0.2.1
    app.kubernetes.io/name: jetscale
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
      backendRefs:
        - name: jetscale-backend-api
          port: 80
          weight: 1
