---
# Source: jetscale/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-jetscale
  labels:
    helm.sh/chart: jetscale-0.2.1
    app.kubernetes.io/name: jetscale
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    alb.ingress.kubernetes.io/actions.jetscale-encrypted-root: |
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"jetscale-backend-api","servicePort":"8000"}]}}
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:081373342681:certificate/ac554daa-f015-41c0-88f6-c41b147d53c6
    alb.ingress.kubernetes.io/conditions.jetscale-encrypted-root: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "JetScale-Request-Encryption-Enabled", "values":["true", "True", "TRUE"]}}]
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=3600
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: "jetscale.staging.jetscale.ai"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-encrypted-root
                port:
                  number: use-annotation
          - path: /openapi.json
            pathType: Prefix
            backend:
              service:
                name: test-backend-api
                port:
                  number: 8000
          - path: /redoc
            pathType: Prefix
            backend:
              service:
                name: test-backend-api
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: test-backend-api
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: test-backend-api
                port:
                  number: 8000
          - path: /api/v1/ws
            pathType: Prefix
            backend:
              service:
                name: test-backend-ws
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-frontend
                port:
                  number: 80
