---
# Source: jetscale/templates/psql.yaml
apiVersion: v1
kind: Service
metadata:
  name: jetscale-postgres
  labels:
    helm.sh/chart: jetscale-0.2.1
    app.kubernetes.io/name: jetscale
    app.kubernetes.io/instance: jetscale
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: jetscale
    app.kubernetes.io/instance: jetscale
    app.kubernetes.io/component: postgres
---
# Source: jetscale/templates/psql.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jetscale-postgres
  labels:
    helm.sh/chart: jetscale-0.2.1
    app.kubernetes.io/name: jetscale
    app.kubernetes.io/instance: jetscale
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: jetscale-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jetscale
      app.kubernetes.io/instance: jetscale
      app.kubernetes.io/component: postgres    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jetscale
        app.kubernetes.io/instance: jetscale
        app.kubernetes.io/component: postgres    
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: jetscale
            - name: POSTGRES_PASSWORD
              value: change-me
            - name: POSTGRES_DB
              value: jetscale
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 8Gi
