apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: jetscale-secrets-store-staging
  namespace: test-jetscale-staging
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: jetscale-external-secrets
      region: us-east-1
      service: SecretsManager
