---
# Source: jetscale/charts/frontend/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-frontend
  labels:
    helm.sh/chart: frontend-2.1.0
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
